--------------------------------------------------------
--  File created - Perþembe-Ocak-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Trigger LOG_TRIGGER_PERSONEL
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."LOG_TRIGGER_PERSONEL" 
AFTER INSERT OR UPDATE OR DELETE 
ON PERSONEL
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
declare
begin
 if inserting then
 INSERT INTO LOGS(LOGTYPE,RELATEDTABLE,RELATEDID,LOGTIME)
VALUES('INSERT','PERSONEL',:NEW.SICILNO,LOCALTIMESTAMP);
elsif updating then
 INSERT INTO LOGS(LOGTYPE,RELATEDTABLE,RELATEDID,LOGTIME)
VALUES('UPDATE','PERSONEL',:OLD.SICILNO,LOCALTIMESTAMP);
 ELSIF deleting THEN
 INSERT INTO LOGS(LOGTYPE,RELATEDTABLE,RELATEDID,LOGTIME)
VALUES('DELETE','PERSONEL',:OLD.SICILNO,LOCALTIMESTAMP);
 END IF;
 END LOG_TRIGGER_PERSONEL;
/
ALTER TRIGGER "SYSTEM"."LOG_TRIGGER_PERSONEL" ENABLE;
